const categoryKeys=['all','drinks','grocery','appetizers','sweets','cheese','spices','fruits'];
// category|name|description|price|emoji|rating|reviews|badge
const rows=`drinks|كوكاكولا كلاسيك|عبوة 12 علبة 330مل|85000|🥤|4.8|124|hot
drinks|كوكاكولا زيرو|بدون سكر، عبوة 12 علبة|85000|🧊|4.5|89
drinks|7Up|علبة 330مل|15000|🍋|4.3|56
drinks|فانتا برتقال|علبة 330مل|15000|🍊|4.4|67
drinks|سبرايت|علبة 330مل|15000|🥤|4.2|45
drinks|بيبسي|علبة 330مل|15000|🥤|4.3|52
drinks|كابري سون كولا|10 علب 200مل|45000|🧃|4.6|78|new
drinks|ليبتون آيس تي خوخ|علبة 330مل|20000|🍹|4.4|61
drinks|مياه معدنية|عبوة 1.5 لتر|8000|💧|4.7|112
drinks|عصير برتقال|عبوة 1 لتر|35000|🍊|4.5|83
grocery|رز أبو كاس|5 كيلو — أرز بسمتي|45000|🍚|4.9|156
grocery|برغل ناعم|1 كيلو غرام|12000|🌾|4.4|48
grocery|عدس أحمر|1 كيلو غرام|15000|🫘|4.3|42
grocery|فاصولياء بيضاء|1 كيلو غرام|18000|🫘|4.5|55
grocery|حمص حب|1 كيلو غرام|14000|🫘|4.4|39
grocery|طحين|2 كيلو غرام|12000|🌾|4.6|67
grocery|سكر|1 كيلو غرام|8000|🍬|4.5|72
grocery|زيت دوار الشمس|1 لتر|45000|🫒|4.7|98
grocery|زيت زيتون|750 مل|65000|🫒|4.9|134
grocery|معكرونة|500 غرام|8000|🍝|4.3|44
grocery|فريكة|1 كيلو غرام|22000|🌾|4.6|58
grocery|شعيرية|500 غرام|7000|🍜|4.2|36
appetizers|حمص بالطحينة|400 غرام|18000|🫓|4.7|89
appetizers|متبل بيروتي|400 غرام|16000|🍆|4.5|67
appetizers|بابا غنوج|400 غرام|15000|🍆|4.6|73
appetizers|تبولة|400 غرام|14000|🥗|4.4|52
appetizers|سلطة فتوش|400 غرام|12000|🥗|4.3|48
appetizers|زعتر بلدي|250 غرام|10000|🌿|4.8|95
appetizers|مكدوس|500 غرام|35000|🍆|4.7|82|new
appetizers|يالنجي|400 غرام|28000|🥬|4.5|61
appetizers|مسبحة|400 غرام|16000|🫓|4.4|55
appetizers|فول مدمس|400 غرام|10000|🫘|4.6|71
sweets|حلاوة الجبن|500 غرام|45000|🍯|4.8|112
sweets|بقلاوة|500 غرام|55000|🥮|4.9|145
sweets|كنافة|500 غرام|40000|🍮|4.7|98
sweets|معتمر|500 غرام|35000|🍪|4.5|67
sweets|تمر مجدول|1 كيلو غرام|60000|🌴|4.8|123
sweets|عسل طبيعي|500 غرام|75000|🍯|4.9|156
sweets|مربى فراولة|400 غرام|18000|🍓|4.4|53
sweets|طحينة|500 غرام|25000|🥜|4.6|78
sweets|دبس رمان|500 مل|22000|🍇|4.5|62
sweets|دبس فليفلة|650 غرام|20000|🌶️|4.3|47
cheese|جبنة حلوم|500 غرام|55000|🧀|4.7|98
cheese|جبنة شلل|500 غرام|45000|🧀|4.5|72
cheese|جبنة بلدية|500 غرام|35000|🧀|4.4|58
cheese|لبنة بقري|400 غرام|28000|🥛|4.6|81
cheese|جبنة قشقوان|500 غرام|60000|🧀|4.8|115
cheese|مرتديلا|500 غرام|35000|🥩|4.3|49
cheese|بسطرمة|300 غرام|75000|🥩|4.7|87
cheese|سجق|500 غرام|45000|🌭|4.4|56
cheese|لحم بعجين|4 قطع|30000|🥟|4.5|68
cheese|كبة|500 غرام|40000|🥟|4.6|79
spices|زعتر|250 غرام|12000|🌿|4.7|86
spices|كمون|250 غرام|10000|🧂|4.5|63
spices|بابريكا|250 غرام|12000|🌶️|4.4|52
spices|قرفة|250 غرام|15000|🫚|4.6|71
spices|فلفل أسود|250 غرام|14000|🌶️|4.5|58
spices|سماق|250 غرام|18000|🍋|4.7|74
spices|بهارات مشكلة|250 غرام|16000|🧂|4.8|92
spices|كركم|250 غرام|10000|🟡|4.4|48
spices|هيل|100 غرام|35000|🌿|4.8|85
spices|زعفران|5 غرام|95000|🌺|4.9|132
fruits|بندورة|1 كيلو غرام|8000|🍅|4.3|41
fruits|خيار|1 كيلو غرام|6000|🥒|4.2|38
fruits|بصل|1 كيلو غرام|5000|🧅|4.4|45
fruits|ثوم|500 غرام|12000|🧄|4.5|52
fruits|بطاطا|2 كيلو غرام|10000|🥔|4.3|44
fruits|باذنجان|1 كيلو غرام|7000|🍆|4.2|37
fruits|كوسا|1 كيلو غرام|8000|🥒|4.1|33
fruits|ليمون|1 كيلو غرام|12000|🍋|4.5|49
fruits|تفاح أحمر|1 كيلو غرام|18000|🍎|4.6|57
fruits|موز|1 كيلو غرام|15000|🍌|4.4|43`;
const productPhotoIds=new Set([1, 8, 9, 11, 12, 13, 14, 15, 18, 19, 21, 22, 23, 24, 25, 26, 29, 31, 33, 35, 37, 38, 39, 40, 44, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 59, 60, 61, 63, 64, 65, 68, 70]);
const products=rows.split('\n').map((line,id)=>{const [cat,name,desc,price,emoji,rating,reviews,badge]=line.split('|');return {id,cat,name,desc,price:+price,emoji,rating:+rating,reviews:+reviews,badge}});
const productNames={
en:['Coca-Cola Classic','Coca-Cola Zero','7Up','Fanta Orange','Sprite','Pepsi','Capri-Sun Cola','Lipton Peach Iced Tea','Mineral Water','Orange Juice','Abu Kass Rice','Fine Bulgur','Red Lentils','White Beans','Chickpeas','Flour','Sugar','Sunflower Oil','Olive Oil','Pasta','Freekeh','Vermicelli','Hummus with Tahini','Beiruti Mutabbal','Baba Ghanoush','Tabbouleh','Fattoush Salad','Syrian Zaatar','Makdous','Yalanji','Musabaha','Fava Beans','Halawet El Jibn','Baklava','Kunafa','Maamoul','Medjool Dates','Natural Honey','Strawberry Jam','Tahini','Pomegranate Molasses','Red Pepper Paste','Halloumi Cheese','String Cheese','White Cheese','Cow Labneh','Kashkaval Cheese','Mortadella','Pastrami','Sujuk','Lahm bi Ajeen','Kibbeh','Zaatar','Cumin','Paprika','Cinnamon','Black Pepper','Sumac','Mixed Spices','Turmeric','Cardamom','Saffron','Tomatoes','Cucumbers','Onions','Garlic','Potatoes','Eggplant','Zucchini','Lemons','Red Apples','Bananas'],
de:['Coca-Cola Classic','Coca-Cola Zero','7Up','Fanta Orange','Sprite','Pepsi','Capri-Sun Cola','Lipton Eistee Pfirsich','Mineralwasser','Orangensaft','Abu-Kass-Reis','Feiner Bulgur','Rote Linsen','Weiße Bohnen','Kichererbsen','Mehl','Zucker','Sonnenblumenöl','Olivenöl','Nudeln','Freekeh','Fadennudeln','Hummus mit Tahini','Beiruti Mutabbal','Baba Ghanoush','Taboulé','Fattoush-Salat','Syrischer Zaatar','Makdous','Yalanji','Musabaha','Saubohnen','Halawet El Jibn','Baklava','Kunafa','Maamoul','Medjool-Datteln','Naturhonig','Erdbeermarmelade','Tahini','Granatapfelmelasse','Paprikapaste','Halloumi','Fadenkäse','Weißkäse','Kuhmilch-Labneh','Kashkaval-Käse','Mortadella','Pastirma','Sucuk','Lahm bi Ajeen','Kibbeh','Zaatar','Kreuzkümmel','Paprika','Zimt','Schwarzer Pfeffer','Sumach','Gewürzmischung','Kurkuma','Kardamom','Safran','Tomaten','Gurken','Zwiebeln','Knoblauch','Kartoffeln','Auberginen','Zucchini','Zitronen','Rote Äpfel','Bananen']
};
const i18n={
ar:{announcement:'توصيل مجاني للطلبات فوق <strong>50,000 ل.س</strong> ✦ نكهة البلد، لعند باب البيت',shopNow:'تسوّق الآن',checkout:'إتمام الطلب',cart:'السلة',heroEyebrow:'من قلب دمشق إلى بيتك',heroTitle:'كل ما تحبّه<br><em>من خيرات بلدنا.</em>',heroText:'بقالة، مقبلات، حلويات، ومشروبات في مكان واحد. اختر منتجاتك وأرسل طلبك عبر واتساب بخطوات بسيطة.',browse:'تصفّح المنتجات',clearPrices:'أسعار واضحة بالليرة السورية',feature1Title:'تسوق مريح',feature1Text:'كل احتياجاتك في مكان واحد',feature2Title:'توصيل لباب البيت',feature2Text:'اطلب وحدد موعدك المناسب',feature3Title:'نكهات سورية',feature3Text:'منتجات مألوفة بتحبّها',catalogEyebrow:'تسوّق على راحتك',productsTitle:'منتجاتنا',productsText:'اختر من الأقسام، واملأ سلّتك بما يلزمك.',sortBy:'ترتيب حسب',currencyNote:'جميع الأسعار بالليرة السورية',noResults:'لا توجد منتجات مطابقة. جرّب كلمة بحث أخرى.',oneStep:'بقيت خطوة',orderDetails:'تفاصيل طلبك',orderText:'أضف بياناتك وحدد موعداً مناسباً، ثم أرسل الطلب عبر واتساب.',step1:'اختر منتجاتك',step2:'حدد الموعد',step3:'أرسل الطلب',yourDetails:'بياناتك وموعد الاستلام',name:'الاسم',phone:'رقم الهاتف',day:'اليوم',time:'الساعة',sendLocation:'⌖ أرسل موقعك للتوصيل',locationHelp:'يمكنك مشاركة موقعك الحالي عند السماح للمتصفح بذلك.',orderTotal:'مجموع الطلب',sendWhatsApp:'إرسال الطلب عبر واتساب',whatsappHelp:'سيفتح واتساب مع تفاصيل طلبك لتراجعها قبل الإرسال.',footerText:'متجرك العربي — بقالة، مقبلات، حلويات، ومشروبات.',copyright:'© 2026 ماركت دمشق الحديثة — موقع تجريبي',yourChoices:'اختياراتك',shoppingCart:'سلة المشتريات',apply:'تطبيق',total:'المجموع',checkoutArrow:'إتمام الطلب ←',clearCart:'مسح السلة',items:'منتجات',viewCart:'عرض السلة ←',search:'ابحث عن منتج...',fullName:'اسمك الكامل',optional:'اختياري',coupon:'رمز الخصم',product:'منتج',products:'منتجات',emptyCart:'سلتك فارغة<br>أضف بعض المنتجات!',new:'جديد',hot:'الأكثر طلباً',add:'إضافة',increase:'زيادة',decrease:'تقليل',currency:'ل.س',couponOk:'تم تطبيق رمز الخصم',couponBad:'رمز الخصم غير صحيح',locationUnavailable:'الموقع غير متاح على هذا الجهاز',locating:'جارٍ تحديد موقعك...',locationDone:'تم تحديد موقعك وسيضاف إلى رسالة الطلب',locationFailed:'تعذّر تحديد الموقع. يمكنك إرساله يدوياً في واتساب.',categories:['الكل','مشروبات','بقالة','مقبلات','حلويات','أجبان ولحوم','بهارات','خضار وفواكه'],sort:['الافتراضي','السعر: من الأرخص','السعر: من الأغلى','الأعلى تقييماً','الأكثر شعبية'],days:['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],today:'اليوم',tomorrow:'غداً'},
de:{announcement:'Kostenlose Lieferung ab <strong>50.000 SYP</strong> ✦ Der Geschmack der Heimat bis an deine Tür',shopNow:'Jetzt einkaufen',checkout:'Bestellung abschließen',cart:'Warenkorb',heroEyebrow:'Von Damascus direkt zu dir',heroTitle:'Alles, was du liebst.<br><em>Aus unserer Heimat.</em>',heroText:'Lebensmittel, Vorspeisen, Süßigkeiten und Getränke an einem Ort. Produkte auswählen und einfach per WhatsApp bestellen.',browse:'Produkte ansehen',clearPrices:'Klare Preise in syrischen Pfund',feature1Title:'Bequem einkaufen',feature1Text:'Alles, was du brauchst, an einem Ort',feature2Title:'Lieferung nach Hause',feature2Text:'Bestellen und passenden Termin wählen',feature3Title:'Syrischer Geschmack',feature3Text:'Vertraute Produkte, die du liebst',catalogEyebrow:'Ganz in Ruhe einkaufen',productsTitle:'Unsere Produkte',productsText:'Kategorie wählen und den Warenkorb füllen.',sortBy:'Sortieren nach',currencyNote:'Alle Preise in syrischen Pfund',noResults:'Keine passenden Produkte gefunden. Versuche einen anderen Suchbegriff.',oneStep:'Nur noch ein Schritt',orderDetails:'Deine Bestellung',orderText:'Daten und Lieferzeit eingeben, dann die Bestellung per WhatsApp senden.',step1:'Produkte wählen',step2:'Zeit wählen',step3:'Bestellung senden',yourDetails:'Daten und Lieferzeit',name:'Name',phone:'Telefonnummer',day:'Tag',time:'Uhrzeit',sendLocation:'⌖ Standort für Lieferung senden',locationHelp:'Du kannst deinen Standort teilen, wenn du dem Browser den Zugriff erlaubst.',orderTotal:'Gesamtsumme',sendWhatsApp:'Bestellung per WhatsApp senden',whatsappHelp:'WhatsApp öffnet sich mit deiner Bestellung zur Kontrolle.',footerText:'Dein arabischer Markt — Lebensmittel, Vorspeisen, Süßigkeiten und Getränke.',copyright:'© 2026 Damascus Modern Market — Demo-Website',yourChoices:'Deine Auswahl',shoppingCart:'Warenkorb',apply:'Anwenden',total:'Summe',checkoutArrow:'Zur Bestellung →',clearCart:'Warenkorb leeren',items:'Produkte',viewCart:'Warenkorb ansehen →',search:'Produkt suchen...',fullName:'Vollständiger Name',optional:'Optional',coupon:'Rabattcode',product:'Produkt',products:'Produkte',emptyCart:'Dein Warenkorb ist leer.<br>Füge einige Produkte hinzu!',new:'Neu',hot:'Bestseller',add:'Hinzufügen',increase:'Mehr',decrease:'Weniger',currency:'SYP',couponOk:'Rabattcode wurde angewendet',couponBad:'Rabattcode ist ungültig',locationUnavailable:'Standort ist auf diesem Gerät nicht verfügbar',locating:'Standort wird ermittelt...',locationDone:'Standort wurde zur Bestellung hinzugefügt',locationFailed:'Standort konnte nicht ermittelt werden. Du kannst ihn in WhatsApp senden.',categories:['Alle','Getränke','Lebensmittel','Vorspeisen','Süßigkeiten','Käse & Fleisch','Gewürze','Obst & Gemüse'],sort:['Standard','Preis: günstig zuerst','Preis: teuer zuerst','Beste Bewertung','Beliebteste'],days:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],today:'Heute',tomorrow:'Morgen'},
en:{announcement:'Free delivery on orders over <strong>50,000 SYP</strong> ✦ A taste of home, delivered to your door',shopNow:'Shop now',checkout:'Checkout',cart:'Cart',heroEyebrow:'From Damascus to your home',heroTitle:'Everything you love.<br><em>From our homeland.</em>',heroText:'Groceries, appetizers, sweets, and drinks in one place. Pick your products and order easily through WhatsApp.',browse:'Browse products',clearPrices:'Clear prices in Syrian pounds',feature1Title:'Easy shopping',feature1Text:'Everything you need in one place',feature2Title:'Home delivery',feature2Text:'Order and choose a good delivery time',feature3Title:'Syrian flavors',feature3Text:'Familiar products you love',catalogEyebrow:'Shop at your own pace',productsTitle:'Our products',productsText:'Choose a category and fill your cart.',sortBy:'Sort by',currencyNote:'All prices are in Syrian pounds',noResults:'No matching products. Try another search word.',oneStep:'One step left',orderDetails:'Your order details',orderText:'Add your details and delivery time, then send the order through WhatsApp.',step1:'Choose products',step2:'Choose a time',step3:'Send the order',yourDetails:'Your details and delivery time',name:'Name',phone:'Phone number',day:'Day',time:'Time',sendLocation:'⌖ Send your location for delivery',locationHelp:'You can share your location when you allow browser access.',orderTotal:'Order total',sendWhatsApp:'Send order through WhatsApp',whatsappHelp:'WhatsApp will open with your order so you can check it before sending.',footerText:'Your Arabic market — groceries, appetizers, sweets, and drinks.',copyright:'© 2026 Damascus Modern Market — Demo website',yourChoices:'Your choices',shoppingCart:'Shopping cart',apply:'Apply',total:'Total',checkoutArrow:'Checkout →',clearCart:'Clear cart',items:'Items',viewCart:'View cart →',search:'Search for a product...',fullName:'Full name',optional:'Optional',coupon:'Discount code',product:'product',products:'products',emptyCart:'Your cart is empty.<br>Add some products!',new:'New',hot:'Bestseller',add:'Add',increase:'Increase',decrease:'Decrease',currency:'SYP',couponOk:'Discount code applied',couponBad:'Invalid discount code',locationUnavailable:'Location is not available on this device',locating:'Finding your location...',locationDone:'Your location was added to the order',locationFailed:'Could not find your location. You can send it in WhatsApp.',categories:['All','Drinks','Groceries','Appetizers','Sweets','Cheese & Meat','Spices','Fruit & Vegetables'],sort:['Default','Price: low to high','Price: high to low','Best rating','Most popular'],days:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],today:'Today',tomorrow:'Tomorrow'}
};
const $=id=>document.getElementById(id);let lang=localStorage.getItem('daryaLang')||'ar';if(!i18n[lang])lang='ar';const tr=key=>i18n[lang][key];const fmt=n=>n.toLocaleString(lang==='de'?'de-DE':'en-US')+' '+tr('currency');let cart={};try{cart=JSON.parse(localStorage.getItem('daryaCart')||'{}')}catch{}let cat='all',sort='default',coupon='',customerLocation=null;
function productName(p){return lang==='ar'?p.name:productNames[lang][p.id]}
function productDesc(p){if(lang==='ar')return p.desc;let d=p.desc;if(lang==='de')return d.replace('بدون سكر، ','Ohne Zucker, ').replace('عبوة 12 علبة','12er-Pack Dosen').replace('10 علب','10 Packungen').replace('علبة','Dose').replace('عبوة','Flasche').replace('كيلو غرام','kg').replace('كيلو','kg').replace('غرام','g').replace('لتر','Liter').replace('مل','ml').replace('4 قطع','4 Stück').replace('أرز بسمتي','Basmati-Reis');return d.replace('بدون سكر، ','Sugar-free, ').replace('عبوة 12 علبة','Pack of 12 cans').replace('10 علب','10 packs').replace('علبة','Can').replace('عبوة','Bottle').replace('كيلو غرام','kg').replace('كيلو','kg').replace('غرام','g').replace('لتر','liter').replace('مل','ml').replace('4 قطع','4 pieces').replace('أرز بسمتي','Basmati rice')}
const coupons={WELCOME10:{type:'percent',value:10},SAVE20:{type:'percent',value:20},FIRST50:{type:'fixed',value:50000}};
function totalBefore(){return products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0)}function discount(){const c=coupons[coupon];if(!c)return 0;return Math.min(totalBefore(),c.type==='percent'?Math.round(totalBefore()*c.value/100):c.value)}function total(){return totalBefore()-discount()}function count(){return Object.values(cart).reduce((a,b)=>a+b,0)}function save(){localStorage.setItem('daryaCart',JSON.stringify(cart));renderAll()}function change(id,delta){cart[id]=Math.max(0,(cart[id]||0)+delta);if(!cart[id])delete cart[id];save()}
function renderCategories(){const buttons=categoryKeys.map((key,i)=>`<button type="button" data-cat="${key}" class="${cat===key?'active':''}" aria-pressed="${cat===key}">${tr('categories')[i]}</button>`).join('');$('categories').innerHTML=buttons;$('topCategories').innerHTML=buttons}
function renderProducts(){const query=$('search').value.trim().toLowerCase();let list=products.filter(p=>(cat==='all'||p.cat===cat)&&(productName(p)+' '+productDesc(p)+' '+p.name).toLowerCase().includes(query));list=[...list];if(cat==='all'&&sort==='default')list.sort((a,b)=>Number(b.id===0||productPhotoIds.has(b.id))-Number(a.id===0||productPhotoIds.has(a.id)));if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(sort==='popular')list.sort((a,b)=>b.reviews-a.reviews);$('resultCount').textContent=`${list.length} ${list.length===1?tr('product'):tr('products')}`;$('emptyResults').hidden=!!list.length;$('products').innerHTML=list.map(p=>{const name=productName(p),desc=productDesc(p);return `<article class="product"><div class="product-art">${p.id===0?`<img class="product-photo contain" src="coca-cola-can.webp" alt="${name}" loading="lazy">`:productPhotoIds.has(p.id)?`<img class="product-photo ${[1,8,18,37,40,61].includes(p.id)?"contain":""}" src="product-${String(p.id).padStart(2,"0")}.webp" alt="${name}" loading="lazy">`:`<span role="img" aria-label="${name}">${p.emoji}</span>`}${p.badge?`<b class="badge ${p.badge==='new'?'new':''}">${tr(p.badge)}</b>`:''}</div><div class="product-info"><div class="rating">★ ${p.rating.toFixed(1)} <small>(${p.reviews})</small></div><h3>${name}</h3><p>${desc}</p><div class="product-bottom"><strong class="price">${p.price.toLocaleString(lang==='de'?'de-DE':'en-US')} <small>${tr('currency')}</small></strong>${cart[p.id]?`<div class="qty"><button type="button" data-id="${p.id}" data-delta="-1" aria-label="${tr('decrease')} ${name}">−</button><b>${cart[p.id]}</b><button type="button" data-id="${p.id}" data-delta="1" aria-label="${tr('increase')} ${name}">+</button></div>`:`<button type="button" class="add-btn" data-id="${p.id}" data-delta="1" aria-label="${tr('add')} ${name}">+</button>`}</div></div></article>`}).join('')}
function renderCart(){const chosen=products.filter(p=>cart[p.id]);$('cartItems').innerHTML=chosen.length?chosen.map(p=>{const name=productName(p);return `<div class="cart-item"><div class="cart-emoji">${p.emoji}</div><div class="cart-item-main"><strong>${name}</strong><small>${productDesc(p)}</small><div class="qty"><button type="button" data-id="${p.id}" data-delta="-1" aria-label="${tr('decrease')} ${name}">−</button><b>${cart[p.id]}</b><button type="button" data-id="${p.id}" data-delta="1" aria-label="${tr('increase')} ${name}">+</button></div></div><span class="cart-item-price">${fmt(p.price*cart[p.id])}</span></div>`}).join(''):`<div class="empty-cart"><span>🛒</span>${tr('emptyCart')}</div>`;$('cartCount').textContent=count();$('summaryItems').textContent=count()+' '+(count()===1?tr('product'):tr('products'));$('summaryTotal').textContent=fmt(total());$('drawerTotal').textContent=fmt(total());$('sendBtn').disabled=!count();$('cartCheckout').disabled=!count();$('mobileCart').hidden=!count();$('mobileCount').textContent=count();$('mobileTotal').textContent=fmt(total())}
function renderAll(){renderProducts();renderCart()}
function openCart(){ $('cartScrim').hidden=false;$('cartDrawer').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('cartClose').focus()}function closeCart(){$('cartScrim').hidden=true;$('cartDrawer').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');document.body.style.overflow='';$('cartOpen').focus()}
function renderDays(){const selected=$('daySelect').value;$('daySelect').innerHTML='';for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()+i);const opt=document.createElement('option');opt.value=d.toLocaleDateString('en-CA');opt.textContent=i===0?`${tr('today')} (${tr('days')[d.getDay()]})`:i===1?`${tr('tomorrow')} (${tr('days')[d.getDay()]})`:`${tr('days')[d.getDay()]} ${d.getDate()}/${d.getMonth()+1}`;$('daySelect').append(opt)}if(selected)$('daySelect').value=selected}
function applyLanguage(next){lang=next;localStorage.setItem('daryaLang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('ltr',lang!=='ar');document.querySelectorAll('[data-i18n]').forEach(el=>{const value=tr(el.dataset.i18n);if(value!==undefined)el.innerHTML=value});document.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.setAttribute('aria-pressed',String(b.dataset.lang===lang))});$('search').placeholder=tr('search');$('customerName').placeholder=tr('fullName');$('customerPhone').placeholder=tr('optional');$('couponInput').placeholder=tr('coupon');[...$('sort').options].forEach((o,i)=>o.textContent=tr('sort')[i]);document.title=lang==='ar'?'ماركت دمشق الحديثة | تسوّق من دمشق':lang==='de'?'Damascus Modern Market | Syrische Produkte':'Damascus Modern Market | Syrian Products';renderDays();renderCategories();renderAll()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;cat=b.dataset.cat;renderCategories();renderProducts();if(b.closest('#topCategories'))$('catalog').scrollIntoView({behavior:'smooth'})});$('search').addEventListener('input',renderProducts);$('sort').addEventListener('change',e=>{sort=e.target.value;renderProducts()});document.addEventListener('click',e=>{const b=e.target.closest('[data-id][data-delta]');if(b)change(+b.dataset.id,+b.dataset.delta)});document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyLanguage(b.dataset.lang)));$('cartOpen').onclick=openCart;$('mobileCartOpen').onclick=openCart;$('cartClose').onclick=closeCart;$('cartScrim').onclick=closeCart;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('cartDrawer').classList.contains('open'))closeCart()});$('cartCheckout').onclick=()=>{closeCart();$('checkout').scrollIntoView({behavior:'smooth'})};$('clearCart').onclick=()=>{cart={};coupon='';$('couponInput').value='';$('couponMessage').textContent='';save()};$('applyCoupon').onclick=()=>{const code=$('couponInput').value.trim().toUpperCase();if(coupons[code]){coupon=code;$('couponMessage').textContent=tr('couponOk');renderCart()}else{$('couponMessage').textContent=tr('couponBad')}};
for(let h=8;h<=22;h++)for(let m=0;m<60;m+=30){const t=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;const o=document.createElement('option');o.value=o.textContent=t;$('timeSelect').append(o)}
$('locationBtn').onclick=()=>{if(!navigator.geolocation){$('locationStatus').textContent=tr('locationUnavailable');return}$('locationStatus').textContent=tr('locating');navigator.geolocation.getCurrentPosition(pos=>{customerLocation=`https://www.google.com/maps?q=${pos.coords.latitude},${pos.coords.longitude}`;$('locationStatus').textContent=tr('locationDone')},()=>{$('locationStatus').textContent=tr('locationFailed')},{enableHighAccuracy:true,timeout:10000})};
$('orderForm').addEventListener('submit',e=>{e.preventDefault();if(!count())return;const name=$('customerName').value.trim();if(!name){$('customerName').focus();return}const labels=lang==='ar'?{newOrder:'طلب جديد — ماركت دمشق الحديثة',name:'الاسم',phone:'الهاتف',date:'الموعد',at:'الساعة',number:'رقم الطلب',location:'موقع العميل',products:'المنتجات',discount:'الخصم',total:'المجموع',sent:'أُرسل من موقع ماركت دمشق الحديثة'}:lang==='de'?{newOrder:'Neue Bestellung — Damascus Modern Market',name:'Name',phone:'Telefon',date:'Termin',at:'um',number:'Bestellnummer',location:'Kundenstandort',products:'Produkte',discount:'Rabatt',total:'Summe',sent:'Gesendet über Damascus Modern Market'}:{newOrder:'New order — Damascus Modern Market',name:'Name',phone:'Phone',date:'Delivery time',at:'at',number:'Order number',location:'Customer location',products:'Products',discount:'Discount',total:'Total',sent:'Sent from Damascus Modern Market'};let msg=`🛒 *${labels.newOrder}*\n\n👤 ${labels.name}: ${name}\n`;const phone=$('customerPhone').value.trim();if(phone)msg+=`📱 ${labels.phone}: ${phone}\n`;msg+=`📅 ${labels.date}: ${$('daySelect').selectedOptions[0].text} ${labels.at} ${$('timeSelect').value}\n🔖 ${labels.number}: ORD-${Date.now().toString(36).toUpperCase()}\n\n`;if(customerLocation)msg+=`📍 ${labels.location}: ${customerLocation}\n\n`;msg+=`📦 *${labels.products}:*\n`;products.filter(p=>cart[p.id]).forEach(p=>msg+=`${p.emoji} ${productName(p)}: ${cart[p.id]} × ${fmt(p.price)} = ${fmt(cart[p.id]*p.price)}\n`);if(discount())msg+=`\n🎟️ ${labels.discount}: -${fmt(discount())}\n`;msg+=`\n💰 *${labels.total}: ${fmt(total())}*\n\n— ${labels.sent}`;window.open('https://wa.me/491621356262?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer')});
applyLanguage(lang);
// Hero gallery: gentle automatic transitions, with manual controls.
(()=>{const slides=[...document.querySelectorAll('.hero-slide')],dots=[...document.querySelectorAll('#slideDots button')],hero=document.querySelector('.hero-carousel');let active=0,timer;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');function show(n){active=(n+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle('active',i===active));dots.forEach((dot,i)=>{dot.classList.toggle('active',i===active);if(i===active)dot.setAttribute('aria-current','true');else dot.removeAttribute('aria-current')})}function stop(){clearInterval(timer)}function start(){stop();if(!reduced.matches)timer=setInterval(()=>show(active+1),5500)}$('slidePrev').onclick=()=>{show(active-1);start()};$('slideNext').onclick=()=>{show(active+1);start()};dots.forEach((dot,i)=>dot.onclick=()=>{show(i);start()});hero.addEventListener('mouseenter',stop);hero.addEventListener('mouseleave',start);hero.addEventListener('focusin',stop);hero.addEventListener('focusout',e=>{if(!hero.contains(e.relatedTarget))start()});document.addEventListener('visibilitychange',()=>document.hidden?stop():start());reduced.addEventListener('change',start);start()})();
