(()=>{'use strict';const $=id=>document.getElementById(id),api=(window.BALADNA_DELIVERY_API||'').replace(/\/$/,'');let key='';
 const states={preparing:'قيد التحضير',out_for_delivery:'خرج للتوصيل',arrived:'وصل المندوب',delivered:'تم التسليم'};
 function notice(text){$('notice').textContent=text}
 async function call(path,data){if(!api)throw new Error('خدمة التوصيل لم تُربط بعد.');const r=await fetch(api+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذّر الاتصال');return j}
 async function run(form,fn){const b=form.querySelector('button');if(b.disabled)return;b.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{b.disabled=false}}
 async function load(){const c=await call('/admin/couriers');$('couriers').replaceChildren();$('courierSelect').replaceChildren();for(const p of c.couriers){const row=document.createElement('p');row.textContent=p.name+(p.active?' — نشط':' — موقوف');if(p.active){const op=document.createElement('option');op.value=p.id;op.textContent=p.name;$('courierSelect').append(op);const btn=document.createElement('button');btn.textContent='إيقاف';btn.onclick=async()=>{if(confirm('إيقاف '+p.name+' وإلغاء تعيين طلباته الجارية؟')){try{await call('/admin/revoke',{id:p.id});await load()}catch(e){notice(e.message)}}};row.append(' ',btn)}$('couriers').append(row)}const orders=await call('/admin/orders');$('orders').replaceChildren();for(const o of orders.orders){const row=document.createElement('p');row.textContent=o.id+' · '+(states[o.status]||o.status)+' · '+(o.courier||'بلا مندوب');$('orders').append(row)}if(!orders.orders.length)$('orders').textContent='لا توجد طلبات توصيل مؤكدة بعد.'}
 $('login').onsubmit=e=>{e.preventDefault();run($('login'),async()=>{key=$('ownerKey').value.trim();await load();$('ownerKey').value='';$('login').hidden=true;$('manager').hidden=false;notice('تم فتح إدارة التوصيل.')})};
 $('logout').onclick=()=>{key='';$('manager').hidden=true;$('login').hidden=false;$('newKey').textContent='';$('newKey').hidden=true;notice('أُغلقت الإدارة.')};
 $('addCourier').onsubmit=e=>{e.preventDefault();run($('addCourier'),async()=>{const c=await call('/admin/couriers',{name:$('courierName').value});$('newKey').hidden=false;$('newKey').textContent='مفتاح المندوب '+c.name+' (يظهر مرة واحدة):\n'+c.key+'\nأدخله في تطبيق المندوب مع عنوان خدمة التوصيل. احتفظ به سرًا.';await load();notice('تمت إضافة المندوب.')})};
 $('assign').onsubmit=e=>{e.preventDefault();run($('assign'),async()=>{const url=new URL($('trackingLink').value),params=new URLSearchParams(url.hash.slice(1));if(url.origin!==location.origin||!url.pathname.endsWith('/track.html'))throw new Error('استخدم رابط تتبّع من موقع بلدنا.');await call('/admin/orders',{id:params.get('order'),token:params.get('token'),courierId:$('courierSelect').value});await load();notice('تم تأكيد الطلب وتعيينه للمندوب.')})};$('refresh').onclick=()=>run($('orders').parentElement,load);
 if(!api)notice('واجهة إدارة التوصيل جاهزة؛ يلزم ربط خدمة التتبّع لتشغيلها.');
})();
