(()=>{'use strict';const $=id=>document.getElementById(id),api=(window.BALADNA_DELIVERY_API||'').replace(/\/$/,'');let key='',courierRecords=[];
 const states={new:'طلب جديد',cancelled:'ملغي',preparing:'قيد التحضير',out_for_delivery:'خرج للتوصيل',arrived:'وصل المندوب',delivered:'تم التسليم'};
 function notice(text){$('notice').textContent=text}
 async function call(path,data){if(!api)throw new Error('خدمة التوصيل لم تُربط بعد.');const r=await fetch(api+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'تعذّر الاتصال');return j}
 async function run(form,fn){const b=form.querySelector('button');if(b.disabled)return;b.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{b.disabled=false}}
 async function load(){const c=await call('/admin/couriers');courierRecords=c.couriers;$('couriers').replaceChildren();$('courierSelect').replaceChildren();for(const p of c.couriers){const row=document.createElement('p');row.textContent=p.name+(p.active?' — نشط':' — موقوف');if(p.active){const op=document.createElement('option');op.value=p.id;op.textContent=p.name;$('courierSelect').append(op);const btn=document.createElement('button');btn.textContent='إيقاف';btn.onclick=async()=>{if(confirm('إيقاف '+p.name+' وإلغاء تعيين طلباته الجارية؟')){try{await call('/admin/revoke',{id:p.id});await load()}catch(e){notice(e.message)}}};const show=document.createElement('button');show.textContent='إظهار / إخفاء الرمز';const secret=document.createElement('pre');secret.hidden=true;secret.style.direction='ltr';secret.style.userSelect='text';show.onclick=async()=>{if(!secret.hidden){secret.textContent='';secret.hidden=true;return}show.disabled=true;try{let result=await call('/admin/key',{id:p.id});if(result.legacy){if(!confirm('رمز هذا المندوب قديم ولا يمكن استرجاعه. إصدار رمز مبسّط جديد سيوقف الرمز القديم، ويجب إدخاله في هاتف المندوب. إصدار الجديد؟'))return;result=await call('/admin/key',{id:p.id,replace:true})}secret.textContent=result.key;secret.hidden=false;notice('يمكنك تحديد الرمز ونسخه. أدخله في تطبيق المندوب.')}catch(e){notice(e.message)}finally{show.disabled=false}};row.append(' ',show,' ',btn,secret)}$('couriers').append(row)}const orders=await call('/admin/orders');allOrders=orders.orders;paintOrders()}
 $('login').onsubmit=e=>{e.preventDefault();run($('login'),async()=>{key=$('ownerKey').value.trim();await load();await loadControls();$('ownerKey').value='';$('login').hidden=true;$('manager').hidden=false;notice('تم فتح إدارة التوصيل.')})};
 $('logout').onclick=()=>{key='';$('manager').hidden=true;$('login').hidden=false;allOrders=[];courierRecords=[];shopDraft=null;shopCatalog=[];$('regionsEditor').replaceChildren();$('bundlesEditor').replaceChildren();$('newKey').textContent='';$('newKey').hidden=true;$('couriers').replaceChildren();$('courierSelect').replaceChildren();$('orders').replaceChildren();notice('أُغلقت الإدارة.')};
 $('addCourier').onsubmit=e=>{e.preventDefault();run($('addCourier'),async()=>{const c=await call('/admin/couriers',{name:$('courierName').value});$('newKey').hidden=false;$('newKey').textContent='مفتاح المندوب '+c.name+' (يمكن إظهاره لاحقًا من زر إظهار الرمز):\n'+c.key+'\nأدخله في تطبيق المندوب مع عنوان خدمة التوصيل. احتفظ به سرًا.';await load();notice('تمت إضافة المندوب.')})};
 $('assign').onsubmit=e=>{e.preventDefault();run($('assign'),async()=>{const url=new URL($('trackingLink').value),params=new URLSearchParams(url.hash.slice(1));if(url.origin!==location.origin||!url.pathname.endsWith('/track.html'))throw new Error('استخدم رابط تتبّع من موقع بلدنا.');await call('/admin/orders',{id:params.get('order'),token:params.get('token'),courierId:$('courierSelect').value});await load();notice('تم تأكيد الطلب وتعيينه للمندوب.')})};$('refresh').onclick=()=>run($('orders').parentElement,load);
 if(!api)notice('واجهة إدارة التوصيل جاهزة؛ يلزم ربط خدمة التتبّع لتشغيلها.');
// Loaded inside the administration closure; never store the owner key in local storage.
let shopDraft=null,shopCatalog=[],allOrders=[];
const txt=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e};
function action(text,fn){const b=txt('button',text);b.type='button';b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{b.disabled=false}};return b}
function productSelect(){const select=document.createElement('select');for(const p of shopCatalog){const o=txt('option',p.name);o.value=p.id;select.append(o)}return select}
function paintOrders(){const host=$('orders');host.replaceChildren();const q=$('orderSearch').value.trim().toLowerCase(),filter=$('orderFilter').value;for(const o of allOrders){if(filter!=='all'&&o.status!==filter)continue;if(q&&!((o.id+' '+(o.details?.name||'')+' '+(o.details?.phone||'')).toLowerCase().includes(q)))continue;const card=document.createElement('article');card.className='admin-order';card.append(txt('h3',o.id+' — '+(states[o.status]||o.status)));const d=o.details;if(d){card.append(txt('p',d.name+' | '+d.phone),txt('p','العنوان: '+d.address+(d.region?' — '+d.region:'')),txt('p','الموعد: '+d.day+' '+d.time),txt('p','الملاحظات: '+(d.notes||'لا توجد')),txt('p','الاستبدال: '+(d.substitution==='allow'?'يمكن اقتراح بديل':'اتصل قبل الاستبدال')));if(d.location){const a=txt('a','فتح موقع الزبون');a.href=d.location;a.target='_blank';a.rel='noopener noreferrer';card.append(a)}const ul=document.createElement('ul');for(const i of d.items)ul.append(txt('li',i.name+' × '+i.quantity+' | '+(i.quantity*i.unitPrice).toLocaleString()+' ل.س'));card.append(ul,txt('strong','المجموع: '+d.total.toLocaleString()+' ل.س | توصيل: '+d.fee.toLocaleString()+' | خصم: '+d.discount.toLocaleString()));}
card.append(txt('p','المندوب: '+(o.courier||'لم يعيّن')));
if(o.status==='new')card.append(action('قبول وتجهيز الطلب',async()=>{await call('/admin/decision',{id:o.id,status:'preparing'});await load()}),action('رفض الطلب',async()=>{if(confirm('رفض هذا الطلب؟')){await call('/admin/decision',{id:o.id,status:'cancelled'});await load()}}));
if(o.status==='preparing'){const select=document.createElement('select');for(const c of courierRecords.filter(c=>c.active)){const op=txt('option',c.name);op.value=c.id;select.append(op)}card.append(select,action('تعيين المندوب',async()=>{if(!select.value)throw Error('أضف مندوبًا نشطًا أولًا');await call('/admin/assign',{id:o.id,courierId:select.value});await load()}));}
if(d&&!['delivered','cancelled'].includes(o.status)){const estimate=document.createElement('input');estimate.maxLength=120;estimate.placeholder='مثال: سيصل خلال ٣٠–٤٥ دقيقة';estimate.value=o.estimate||'';card.append(estimate,action('حفظ وقت الوصول المتوقع',async()=>{await call('/admin/estimate',{id:o.id,estimate:estimate.value});notice('حُفظ تقدير الوصول.')}));}host.append(card)}if(!host.children.length)host.textContent='لا توجد طلبات مطابقة.';}
function regionEditor(r){const row=document.createElement('div');row.className='admin-grid region-row';const name=document.createElement('input');name.placeholder='اسم المنطقة';name.value=r.name;name.maxLength=80;name.dataset.field='name';const fee=document.createElement('input');fee.type='number';fee.min=0;fee.placeholder='رسوم التوصيل';fee.value=r.fee;fee.dataset.field='fee';const minimum=document.createElement('input');minimum.type='number';minimum.min=0;minimum.placeholder='الحد الأدنى';minimum.value=r.minimum;minimum.dataset.field='minimum';const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=r.enabled!==false;enabled.dataset.field='enabled';const label=txt('label','ضمن الخدمة');label.append(enabled);row.append(name,fee,minimum,label,action('حذف المنطقة',async()=>row.remove()));$('regionsEditor').append(row);}
function bundleEditor(b){const box=document.createElement('div');box.className='bundle-editor';box.dataset.id=b.id;const name=document.createElement('input');name.value=b.name;name.placeholder='اسم الحزمة';name.maxLength=80;name.dataset.field='bundleName';const percent=document.createElement('input');percent.type='number';percent.min=0;percent.max=80;percent.value=b.percent;percent.dataset.field='percent';box.append(txt('label','اسم الحزمة'),name,txt('label','نسبة الخصم (٠–٨٠٪)'),percent);const items=document.createElement('div');items.className='bundle-items';const addItem=i=>{const row=document.createElement('div');const select=productSelect();select.value=i.id;const quantity=document.createElement('input');quantity.type='number';quantity.min=1;quantity.max=99;quantity.value=i.quantity;row.append(select,quantity,action('حذف المنتج',async()=>row.remove()));items.append(row)};for(const i of b.items)addItem(i);box.append(items,action('إضافة منتج للحزمة',async()=>addItem({id:shopCatalog[0]?.id,quantity:1})),action('حذف الحزمة',async()=>box.remove()));$('bundlesEditor').append(box);}
function paintStock(){const host=$('stockList');host.replaceChildren();for(const [id,v]of Object.entries(shopDraft.stock)){if(v===false)host.append(txt('p','نفد المخزون: '+(shopCatalog.find(p=>p.id===+id)?.name||id)))}if(!host.children.length)host.textContent='كل المنتجات متوفرة.';}
async function loadControls(){try{const d=await call('/admin/settings');if(d.version!==3)return;shopDraft=d;$('shopControls').hidden=false;for(const f of ['paused','manualOpen','useHours'])$(f).checked=d[f];$('openTime').value=d.open;$('closeTime').value=d.close;for(const f of ['etaMin','etaMax','freeAbove'])$(f).value=d[f];$('regionsEditor').replaceChildren();for(const r of d.regions)regionEditor(r);try{shopCatalog=(await call('/admin/catalog')).products;}catch(e){notice('الطلبات متاحة، لكن تعذّر تحميل قائمة المنتجات للإعدادات.');}const select=$('stockProduct');select.replaceChildren();for(const p of shopCatalog){const o=txt('option',p.name);o.value=p.id;select.append(o)}paintStock();$('bundlesEditor').replaceChildren();for(const b of d.bundles)bundleEditor(b);}catch{$('shopControls').hidden=true;}}
$('addRegion').onclick=()=>regionEditor({name:'',fee:0,minimum:0,enabled:true});$('addBundle').onclick=()=>bundleEditor({id:crypto.randomUUID(),name:'',percent:0,items:[]});$('toggleStock').onclick=()=>{if(!shopDraft||!$('stockProduct').value)return;const id=$('stockProduct').value;if(shopDraft.stock[id]===false)delete shopDraft.stock[id];else shopDraft.stock[id]=false;paintStock();notice('تغيير محلي؛ اضغط حفظ جميع الإعدادات لتطبيقه.')};
$('settingsForm').onsubmit=e=>{e.preventDefault();run($('settingsForm'),async()=>{const d={...shopDraft};for(const f of ['paused','manualOpen','useHours'])d[f]=$(f).checked;d.open=$('openTime').value;d.close=$('closeTime').value;for(const f of ['etaMin','etaMax','freeAbove'])d[f]=Number($(f).value);d.regions=[...document.querySelectorAll('.region-row')].map(row=>({name:row.querySelector('[data-field=name]').value,fee:Number(row.querySelector('[data-field=fee]').value),minimum:Number(row.querySelector('[data-field=minimum]').value),enabled:row.querySelector('[data-field=enabled]').checked}));d.bundles=[...document.querySelectorAll('.bundle-editor')].map(box=>({id:box.dataset.id,name:box.querySelector('[data-field=bundleName]').value,percent:Number(box.querySelector('[data-field=percent]').value),items:[...box.querySelector('.bundle-items').children].map(row=>({id:Number(row.querySelector('select').value),quantity:Number(row.querySelector('input').value)}))}));await call('/admin/settings',d);shopDraft=d;notice('حُفظت الإعدادات. حدّث موقع الزبون لرؤية النتيجة.');})};
$('enablePush').onclick=async()=>{try{await call('/admin/push-enable',{});$('pushNotice').textContent='تم تجهيز الخدمة؛ يفعّل الزبون إشعارات طلبه من صفحة التتبع. يلزم اختبارها على هاتف يدعمها.';}catch(e){notice(e.message)}};
$('orderSearch').oninput=paintOrders;$('orderFilter').onchange=paintOrders;

})();

