import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './worker.mjs';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));const DB={prepare(sql){let args=[];return{bind(...a){args=a;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return{results:db.prepare(sql).all(...args)}},async run(){return{meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}}},async batch(stmts){db.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};const env={DB,OWNER_SECRET:'owner-test-secret',SITE_ORIGIN:'https://shop.example'};return{db,async call(path,key,data,origin){const headers={Authorization:'Bearer '+key};if(origin)headers.Origin=origin;const r=await worker.fetch(new Request('https://api.example'+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);return{status:r.status,body:await r.json()}}}}
test('order assignment, courier isolation, freshness, state progression and revocation',async()=>{const f=fixture(),owner='owner-test-secret';assert.equal((await f.call('/admin/orders','bad')).status,401);assert.equal((await f.call('/admin/orders',owner,null,'https://bad.example')).status,403);const a=(await f.call('/admin/couriers',owner,{name:'A'})).body,b=(await f.call('/admin/couriers',owner,{name:'B'})).body;const token='a'.repeat(64);assert.equal((await f.call('/admin/orders',owner,{id:'ORD-TEST',token,courierId:a.id})).status,201);assert.equal((await f.call('/track','b'.repeat(64))).status,404);assert.equal((await f.call('/courier/status',b.key,{id:'ORD-TEST',status:'out_for_delivery'})).status,409);assert.equal((await f.call('/courier/location',a.key,{lat:33.5,lng:36.3,accuracy:10})).body.active,false);assert.equal((await f.call('/courier/status',a.key,{id:'ORD-TEST',status:'delivered'})).status,409);assert.equal((await f.call('/courier/status',a.key,{id:'ORD-TEST',status:'out_for_delivery'})).status,200);assert.equal((await f.call('/courier/location',a.key,{lat:100,lng:36,accuracy:10})).status,400);assert.equal((await f.call('/courier/location',a.key,{lat:33.5,lng:36.3,accuracy:10})).status,200);let tracked=(await f.call('/track',token)).body;assert.equal(tracked.location.lat,33.5);assert.equal(tracked.courier_id,undefined);assert.equal((await f.call('/courier/status',a.key,{id:'ORD-TEST',status:'arrived'})).status,200);assert.equal((await f.call('/track',token)).body.location,null);assert.equal((await f.call('/courier/status',a.key,{id:'ORD-TEST',status:'delivered'})).status,200);assert.equal((await f.call('/courier/status',a.key,{id:'ORD-TEST',status:'delivered'})).status,409);await f.call('/admin/revoke',owner,{id:a.id});assert.equal((await f.call('/courier/orders',a.key)).status,401);f.db.prepare('UPDATE orders SET expires=0').run();assert.equal((await f.call('/track',token)).status,404);f.db.close()});
test('short courier keys are owner-only and replacing legacy keys invalidates the old key',async()=>{const f=fixture(),owner='owner-test-secret';const a=(await f.call('/admin/couriers',owner,{name:'A'})).body;assert.match(a.key,/^[a-f0-9]{4}(-[a-f0-9]{4}){4}$/);assert.equal((await f.call('/admin/key',owner,{id:a.id})).body.key,a.key);assert.equal((await f.call('/admin/key',a.key,{id:a.id})).status,401);const {hash}=await import('./worker.mjs');f.db.prepare('UPDATE couriers SET token_hash=? WHERE id=?').run(await hash('legacy-token'),a.id);assert.equal((await f.call('/admin/key',owner,{id:a.id})).body.legacy,true);assert.equal((await f.call('/admin/key',owner,{id:a.id,replace:true})).body.key,a.key);assert.equal((await f.call('/courier/orders','legacy-token')).status,401);assert.equal((await f.call('/courier/orders',a.key)).status,200);f.db.close()});

test('checkout uses catalog prices, enforces stock and region, and preserves receipt on retry',async()=>{const f=fixture(),owner='owner-test-secret',originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response('baladnaCatalogLoaded({"products":[{"id":1,"name":"Milk","price":10000}]});');try{const settings=(await f.call('/admin/settings',owner)).body;settings.regions=[{name:'Center',fee:2000,minimum:15000,enabled:true}];await f.call('/admin/settings',owner,settings);const order={id:'ORD-CHECK',token:'c'.repeat(64),name:'Customer',phone:'123',address:'Street',region:'1',items:[{id:1,quantity:2,unitPrice:1}]};const made=await f.call('/orders','',order);assert.equal(made.status,201);assert.equal(made.body.details.total,22000);assert.equal(made.body.details.items[0].unitPrice,10000);assert.deepEqual((await f.call('/orders','',order)).body.details,made.body.details);assert.equal((await f.call('/track',order.token)).body.details,undefined);assert.equal((await f.call('/orders','',{...order,id:'ORD-SMALL',items:[{id:1,quantity:1}]})).status,400);settings.stock={'1':false};await f.call('/admin/settings',owner,settings);assert.notEqual((await f.call('/orders','',{...order,id:'ORD-STOCK'})).status,201);settings.stock={};settings.paused=true;await f.call('/admin/settings',owner,settings);assert.equal((await f.call('/orders','',{...order,id:'ORD-CLOSED'})).status,409);}finally{globalThis.fetch=originalFetch;f.db.close()}});
